Release 0.9.0
cartesi/machine-solidity-step pull request #54
Opened 2023-08-14 19:47 UTC by vfusco

2023-08-14 19:52 UTC, mpernambuco approved these changes

2023-08-14 20:21 UTC, edubart requested changes

2023-08-14 20:21 UTC, edubart commented on CHANGELOG.md
> +
I think is important to always mention which emulator release this solidity-step release is expected to work with.

Currently, the main branch is incompatible with the emulator main branch, so we cannot release it yet.

2023-08-17 01:16 UTC, stephenctw commented on CHANGELOG.md
> +- Added `dep` and `depclean` target
`dep` and `depclean` are no longer supported, since we don't install `npm` modules anymore.

2023-08-17 01:16 UTC, stephenctw commented on CHANGELOG.md
> +- Added `dep` and `depclean` target
`commander` is no longer required.

2023-08-17 01:16 UTC, stephenctw commented on CHANGELOG.md
> +- Removed npm-scripts-info package
+ Changed `step` function interface and parameters to be more generic types.

2023-08-17 01:50 UTC, vfusco commented
Cherry picked into #46

2023-08-17 01:50 UTC, closed without merging